export const BingData = [
    {
        aria_label : 'Manmohan Singh',
        title : 'Search for: Manmohan Singh',
        href : 'search8b61.html?q=Manmohan+Singh&FORM=IRMHRS',
        h : 'ID=images,5477.1',
        src2 : 'https://tse1.mm.bing.net/th?q=Manmohan+Singh&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Manmohan Singh',
        first_name : 'Manmohan ',
        last_name : 'Singh',
    },
    {
        aria_label : 'Narendra Modi Biography',
        title : 'Search for: Narendra Modi Biography',
        href : 'search66ff.html?q=Narendra+Modi+Biography&FORM=IRMHRS',
        h : 'ID=images,5479.1',
        src2 : 'https://tse2.mm.bing.net/th?q=Narendra+Modi+Biography&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Narendra Modi Biography',
        first_name : 'Narendra Modi',
        last_name : 'Bio',
    },
    {
        aria_label : 'Narendra Modi Cartoon',
        title : 'Search for: Narendra Modi Cartoon',
        href : 'search17d5.html?q=Narendra+Modi+Cartoon&FORM=IRMHRS',
        h : 'ID=images,5481.1',
        src2 : 'https://tse3.mm.bing.net/th?q=Narendra+Modi+Cartoon&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Narendra Modi Cartoon',
        first_name : 'Narendra Modi',
        last_name : 'Cartoon',
    },
    {
        aria_label : `Narendra Modi's Son`,
        title : `Search for: Narendra Modi's Son`,
        href : 'search6648.html?q=Narendra+Modi%27s+Son&FORM=IRMHRS',
        h : 'ID=images,5483.1',
        src2 : 'https://tse3.mm.bing.net/th?q=Narendra+Modi%27s+Son&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : `Narendra Modi's Son`,
        first_name : `Narendra Modi's`,
        last_name : 'Son',
    },
    {
        aria_label : 'Narendra Modi Drawing',
        title : 'Search for: Narendra Modi Drawing',
        href : 'search338f.html?q=Narendra+Modi+Drawing&FORM=IRMHRS',
        h : 'ID=images,5485.1',
        src2 : 'https://tse3.mm.bing.net/th?q=Narendra+Modi+Drawing&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Narendra Modi Drawing',
        first_name : 'Narendra Modi',
        last_name : 'Drawing',
    },
    {
        aria_label : 'BJP',
        title : 'Search for: BJP',
        href : 'searchd4a3.html?q=BJP&FORM=IRMHRS',
        h : 'ID=images,5487.1',
        src2 : 'https://tse3.mm.bing.net/th?q=BJP&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'BJP',
        first_name : 'BJP',
        last_name : ' ',
    },
    {
        aria_label : 'BJP Modi',
        title : 'Search for: BJP Modi',
        href : 'searche1c6.html?q=BJP+Modi&FORM=IRMHRS',
        h : 'ID=images,5489.1',
        src2 : 'https://tse4.mm.bing.net/th?q=BJP+Modi&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'BJP Modi',
        first_name : 'BJP',
        last_name : 'Modi',
    },
    {
        aria_label : 'Narendra Modi Married',
        title : 'Search for: Narendra Modi Married',
        href : 'search393f.html?q=Narendra+Modi+Married&FORM=IRMHRS',
        h : 'ID=images,5491.1',
        src2 : 'https://tse1.mm.bing.net/th?q=Narendra+Modi+Married&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Narendra Modi Married',
        first_name : 'Narendra Modi',
        last_name : 'Married',
    },
    {
        aria_label : 'Narendra Modi Mother',
        title : 'Search for: Narendra Modi Mother',
        href : 'searche083.html?q=Narendra+Modi+Mother&FORM=IRMHRS',
        h : 'ID=images,5493.1',
        src2 : 'https://tse2.mm.bing.net/th?q=Narendra+Modi+Mother&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Narendra Modi Mother',
        first_name : 'Narendra Modi',
        last_name : 'Mother',
    },
    {
        aria_label : 'Narendra Modi Stadium',
        title : 'Search for: Narendra Modi Stadium',
        href : 'search527c.html?q=Narendra+Modi+Stadium&FORM=IRMHRS',
        h : 'ID=images,5495.1',
        src2 : 'https://tse4.mm.bing.net/th?q=Narendra+Modi+Stadium&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Narendra Modi Stadium',
        first_name : 'Narendra Modi',
        last_name : 'Stadium',
    },
    {
        aria_label : 'Narendra Modi with Hijab',
        title : 'Search for: Narendra Modi with Hijab',
        href : 'searche3cb.html?q=Narendra+Modi+with+Hijab&FORM=IRMHRS',
        h : 'ID=images,5497.1',
        src2 : 'https://tse1.mm.bing.net/th?q=Narendra+Modi+with+Hijab&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Narendra Modi with Hijab',
        first_name : 'Narendra Modi',
        last_name : 'with Hijab',
    },
    {
        aria_label : 'Indian PM Narendra Modi',
        title : 'Search for: Indian PM Narendra Modi',
        href : 'search597a.html?q=Indian+PM+Narendra+Modi&FORM=IRMHRS',
        h : 'ID=images,5499.1',
        src2 : 'https://tse3.mm.bing.net/th?q=Indian+PM+Narendra+Modi&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Indian PM Narendra Modi',
        first_name : 'Indian PM',
        last_name : 'Narendra Modi',
    },
    {
        aria_label : 'Nitish Kumar',
        title : 'Search for: Nitish Kumar',
        href : 'search82f2.html?q=Nitish+Kumar&FORM=IRMHRS',
        h : 'ID=images,5501.1',
        src2 : 'https://tse4.mm.bing.net/th?q=Nitish+Kumar&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Nitish Kumar',
        first_name : 'Nitish',
        last_name : 'Kumar',
    },
    {
        aria_label : 'Modi Ji',
        title : 'Search for: Modi Ji',
        href : 'search4d6c.html?q=Modi+Ji&FORM=IRMHRS',
        h : 'ID=images,5503.1',
        src2 : 'https://tse3.mm.bing.net/th?q=Modi+Ji&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Modi Ji',
        first_name : 'Modi',
        last_name : 'Ji',
    },
    {
        aria_label : 'Narendra Modi Father',
        title : 'Search for: Narendra Modi Father',
        href : 'search83f6.html?q=Narendra+Modi+Father&FORM=IRMHRS',
        h : 'ID=images,5505.1',
        src2 : 'https://tse3.mm.bing.net/th?q=Narendra+Modi+Father&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Narendra Modi Father',
        first_name : 'Narendra Modi',
        last_name : 'Father',
    },
    {
        aria_label : 'Narendra Modi News',
        title : 'Search for: Narendra Modi News',
        href : 'search6409.html?q=Narendra+Modi+News&FORM=IRMHRS',
        h : 'ID=images,5507.1',
        src2 : 'https://tse4.mm.bing.net/th?q=Narendra+Modi+News&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Narendra Modi News',
        first_name : 'Narendra Modi',
        last_name : 'News',
    },
    {
        aria_label : 'Narendra Modi Children',
        title : 'Search for: Narendra Modi Children',
        href : 'search6d91.html?q=Narendra+Modi+Children&FORM=IRMHRS',
        h : 'ID=images,5509.1',
        src2 : 'https://tse2.mm.bing.net/th?q=Narendra+Modi+Children&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Narendra Modi Children',
        first_name : 'Narendra Modi',
        last_name : 'Children',
    },
    {
        aria_label : 'Ratan Tata',
        title : 'Search for: Ratan Tata',
        href : 'searcheb59.html?q=Ratan+Tata&FORM=IRMHRS',
        h : 'ID=images,5511.1',
        src2 : 'https://tse3.mm.bing.net/th?q=Ratan+Tata&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Ratan Tata',
        first_name : 'Ratan',
        last_name : 'Tata',
    },
    {
        aria_label : 'Narendra Modi Personal Life',
        title : 'Search for: Narendra Modi Personal Life',
        href : 'search669a.html?q=Narendra+Modi+Personal+Life&FORM=IRMHRS',
        h : 'ID=images,5513.1',
        src2 : 'https://tse3.mm.bing.net/th?q=Narendra+Modi+Personal+Life&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Narendra Modi Personal Life',
        first_name : 'Narendra Modi',
        last_name : 'Personal Life',
    },
    {
        aria_label : 'Narendra Modi Home',
        title : 'Search for: Narendra Modi Home',
        href : 'search6794.html?q=Narendra+Modi+Home&FORM=IRMHRS',
        h : 'ID=images,5515.1',
        src2 : 'https://tse4.mm.bing.net/th?q=Narendra+Modi+Home&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Narendra Modi Home',
        first_name : 'Narendra Modi',
        last_name : 'Home',
    },
    {
        aria_label : 'Narendra Modi Young Photos',
        title : 'Search for: Narendra Modi Young Photos',
        href : 'search7623.html?q=Narendra+Modi+Young+Photos&FORM=IRMHRS',
        h : 'ID=images,5517.1',
        src2 : 'https://tse2.mm.bing.net/th?q=Narendra+Modi+Young+Photos&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Narendra Modi Young Photos',
        first_name : 'Narendra Modi',
        last_name : 'Young Photos',
    },
    {
        aria_label : 'Imran Khan',
        title : 'Search for: Imran Khan',
        href : 'search7e43.html?q=Imran+Khan&FORM=IRMHRS',
        h : 'ID=images,5519.1',
        src2 : 'https://tse2.mm.bing.net/th?q=Imran+Khan&w=42&h=42&c=1&p=0&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1',
        alt : 'Imran Khan',
        first_name : 'Imran',
        last_name : 'Khan',
    },
    {
        aria_label : '',
        title : '',
        href : '',
        h : '',
        src2 : '',
        alt : '',
        first_name : '',
        last_name : '',
    },
    {
        aria_label : '',
        title : '',
        href : '',
        h : '',
        src2 : '',
        alt : '',
        first_name : '',
        last_name : '',
    },
    {
        aria_label : '',
        title : '',
        href : '',
        h : '',
        src2 : '',
        alt : '',
        first_name : '',
        last_name : '',
    },
    {
        aria_label : '',
        title : '',
        href : '',
        h : '',
        src2 : '',
        alt : '',
        first_name : '',
        last_name : '',
    },
    {
        aria_label : '',
        title : '',
        href : '',
        h : '',
        src2 : '',
        alt : '',
        first_name : '',
        last_name : '',
    },
    {
        aria_label : '',
        title : '',
        href : '',
        h : '',
        src2 : '',
        alt : '',
        first_name : '',
        last_name : '',
    },
    {
        aria_label : '',
        title : '',
        href : '',
        h : '',
        src2 : '',
        alt : '',
        first_name : '',
        last_name : '',
    },
    {
        aria_label : '',
        title : '',
        href : '',
        h : '',
        src2 : '',
        alt : '',
        first_name : '',
        last_name : '',
    },
    {
        aria_label : '',
        title : '',
        href : '',
        h : '',
        src2 : '',
        alt : '',
        first_name : '',
        last_name : '',
    },
    {
        aria_label : '',
        title : '',
        href : '',
        h : '',
        src2 : '',
        alt : '',
        first_name : '',
        last_name : '',
    },
    {
        aria_label : '',
        title : '',
        href : '',
        h : '',
        src2 : '',
        alt : '',
        first_name : '',
        last_name : '',
    },
    {
        aria_label : '',
        title : '',
        href : '',
        h : '',
        src2 : '',
        alt : '',
        first_name : '',
        last_name : '',
    },
    {
        aria_label : '',
        title : '',
        href : '',
        h : '',
        src2 : '',
        alt : '',
        first_name : '',
        last_name : '',
    },
    {
        aria_label : '',
        title : '',
        href : '',
        h : '',
        src2 : '',
        alt : '',
        first_name : '',
        last_name : '',
    },
    {
        aria_label : '',
        title : '',
        href : '',
        h : '',
        src2 : '',
        alt : '',
        first_name : '',
        last_name : '',
    },
    {
        aria_label : '',
        title : '',
        href : '',
        h : '',
        src2 : '',
        alt : '',
        first_name : '',
        last_name : '',
    }
];